version: 0.1

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - echo "Using Python version:"
      - python3 --version  # Should match your Lambda runtime (e.g., Python 3.13)
      - pip3 install requests -t python/
  build:
    commands:
      - zip -r requests_layer.zip python
      - aws lambda publish-layer-version \
          --layer-name requests-layer \
          --zip-file fileb://requests_layer.zip \
          --compatible-runtimes python3.13
